### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by baranpirincal** [rolfwessels/CoreDocker#18]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by rolfwessels** [comment]
Hi Baran,

Wow, I have to say that I am slightly taken aback. I would really like to know why/how you selected this project to design a logo for.

That being said I will take you up on the offer.

Kind regards

Rolf

**Comment by baranpirincal** [comment]
Hey again.

Actually, my motivation is making my portfolio better with supporting open-source projects. I was looking to most active repositories which I contribute that's how I found your project.

Best regards

Baran

**Comment by rolfwessels** [comment]
Hi,

Sorry for the delay. Missed this notification. Sounds great what you are doing. What is the next step ? 

Kind regards

Rolf Wessels

**Comment by rolfwessels** [comment]
Hi,

For CoreDocker, I'm currently using the https://tabler.github.io/tabler/ theme as a UI for the CoreDocker API.

I really like simple geometric logos like
https://www.vectorlogo.zone/logos/gitlab/gitlab-card.png
https://www.stadtgold.co.za/

I don't have any specific colors in mind but I like the idea of orange to yellow range. Ultimately it will be on white background mostly and it will be integrated into the tabler theme.

Also ideally it should be in svg format.

Hope that helps.

Thanks so much.

**Comment by baranpirincal** [comment]
Hey again @rolfwessels ,

I am so sorry for being late, I was so busy last weeks. I completed logo design of Core Docker. I hope you like it! 

I am waiting your comments.

Best Regards
Baran

![coredocker](https://user-images.githubusercontent.com/37786733/45108169-83af5b00-b144-11e8-94a6-d16d0c5c999e.jpg)

![v2](https://user-images.githubusercontent.com/37786733/45108825-75fad500-b146-11e8-9c54-bab2a5be0cde.jpg)


![front](https://user-images.githubusercontent.com/37786733/45108173-890ca580-b144-11e8-98b6-0377a7c67313.jpg)

**Comment by rolfwessels** [comment]
Hi @baranpirincal,

I have to be honest, I was really not sure what to expect and I have to say that I am very plesantly surprised.

I like both versions, the one with the coredocker in the logo and the alternative where it is just  the logo withouth the writing. I can see using the one on the readme and the other one in the dashboards logo.

Thats amazing man, I really impressed, thank you so much.

**Comment by rolfwessels** [comment]
Thanks again.
